/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Информация о владельце токена */
        get: operations["introspectToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск и список событий */
        get: operations["getEvents"];
        put?: never;
        /** Создать событие */
        post: operations["addEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Номер события */
                event_id: number;
            };
            cookie?: never;
        };
        /** Информация о событии */
        get: operations["getSingleEvent"];
        put?: never;
        /** Редактировать событие */
        post: operations["editEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Номер события */
                event_id: number;
            };
            cookie?: never;
        };
        /** Список заказов события */
        get: operations["getEventOrders"];
        put?: never;
        /** Создать заказ (регистрацию) */
        post: operations["addOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
                order_id: number;
            };
            cookie?: never;
        };
        /** Информация о заказе */
        get: operations["getSingleEventOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить заказ */
        patch: operations["editEventOrder"];
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать организацию */
        post: operations["addOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organization_id}/hooks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор организации */
                organization_id: number;
            };
            cookie?: never;
        };
        /** Список webhook'ов организации */
        get: operations["getHooks"];
        put?: never;
        /** Добавить webhook */
        post: operations["addHook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organization_id}/hooks/{hook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: number;
                /** @description Идентификатор webhook'а */
                hook_id: number;
            };
            cookie?: never;
        };
        /** Информация о webhook'е */
        get: operations["getHook"];
        put?: never;
        /** Изменить webhook */
        post: operations["editHook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Информация о владельце токена */
        Introspect: {
            active?: boolean;
            client_id?: string;
            user_id?: string;
            user_email?: string;
            organizations?: components["schemas"]["OrganizationResponse"][];
        };
        EventsResponse: {
            total?: number;
            values?: components["schemas"]["EventResponse"][];
        };
        /** @description Описание создаваемого события */
        CreateEvent: {
            organization: components["schemas"]["OrganizationInclude"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at?: string;
            name: string;
            description_short?: string;
            description_html?: string;
            categories?: components["schemas"]["CategoryInclude"][];
            location?: components["schemas"]["LocationInclude"];
            poster_image_url?: string;
            properties?: string[];
            custom?: {
                [key: string]: unknown;
            };
            questions?: components["schemas"]["QuestionInclude"][];
            /** @enum {string} */
            access_status?: "private" | "draft" | "link_only" | "public";
            ticket_types?: components["schemas"]["TicketTypeRequest"][];
        };
        /** @description Изменяемые поля события */
        EditEvent: {
            ticket_types?: components["schemas"]["TicketTypeRequest"][];
            name?: string;
            description_short?: string;
            description_html?: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            categories?: components["schemas"]["CategoryInclude"][];
            location?: components["schemas"]["LocationInclude"];
            poster_image_url?: string;
            properties?: string[];
            custom?: {
                [key: string]: unknown;
            };
            questions?: components["schemas"]["QuestionInclude"][];
            /** @enum {string} */
            access_status?: "private" | "draft" | "link_only" | "public";
        };
        EventResponse: {
            id?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            name?: string;
            description_short?: string;
            description_html?: string;
            url?: string;
            poster_image?: components["schemas"]["ImageResponse"];
            ad_partner_percent?: number;
            locale?: string;
            location?: components["schemas"]["LocationResponse"];
            organization?: components["schemas"]["OrganizationResponse"];
            categories?: components["schemas"]["CategoryResponse"][];
            ticket_types?: components["schemas"]["TicketTypeResponse"][];
            questions?: components["schemas"]["QuestionResponse"][];
            widgets?: components["schemas"]["WidgetResponse"][];
            properties?: string[];
            moderation_status?: string;
            access_status?: string;
            registration_data?: components["schemas"]["RegistrationDataResponse"];
        };
        OrganizationInclude: {
            id: number;
            subdomain?: string;
        };
        OrganizationResponse: {
            id?: number;
            name?: string;
            description_html?: string;
            url?: string;
            logo_image?: components["schemas"]["ImageResponse"];
            subdomain?: string;
            permissions?: string[];
        };
        CreateOrganization: {
            name: string;
            subdomain?: string;
            phone?: string;
        };
        LocationInclude: {
            city?: string;
            address?: string;
        };
        LocationResponse: {
            country?: string;
            city?: string;
            address?: string;
            coordinates?: number[];
        };
        CategoryInclude: {
            id?: number;
            name?: string;
        };
        CategoryResponse: {
            id?: number;
            name?: string;
        };
        ImageResponse: {
            default_url?: string;
            uploadcare_url?: string;
        };
        TicketTypeRequest: {
            id?: number;
            price?: number;
            status?: string;
            name?: string;
            description?: string;
            /** Format: date-time */
            sale_starts_at?: string;
            /** Format: date-time */
            sale_ends_at?: string;
            limit?: number;
        };
        TicketTypeResponse: {
            id?: number;
            name?: string;
            description?: string;
            buy_amount_min?: number;
            buy_amount_max?: number;
            price?: number;
            is_promocode_locked?: boolean;
            remaining?: number;
            /** Format: date-time */
            sale_ends_at?: string;
            /** Format: date-time */
            sale_starts_at?: string;
            public_key?: string;
            is_active?: boolean;
            ad_partner_profit?: number;
            sold?: number;
            attended?: number;
            limit?: number;
            status?: string;
        };
        QuestionInclude: {
            field_id?: string;
            is_mandatory?: boolean;
            status?: string;
            name?: string;
            comment?: string;
            type?: string;
            possible_answers?: string[];
        };
        QuestionResponse: {
            field_id?: number;
            name?: string;
            comment?: string;
            type?: string;
            possible_answers?: components["schemas"]["AnswerResponse"][];
            is_mandatory?: boolean;
            is_for_every_visitor?: boolean;
            meta?: {
                [key: string]: unknown;
            };
        };
        AnswerResponse: {
            id?: number;
            name?: string;
        };
        WidgetResponse: {
            code_html?: string;
        };
        RegistrationDataResponse: {
            price_max?: number;
            price_min?: number;
            /** Format: date-time */
            sale_ends_at?: string;
            tickets_total?: number;
            tickets_limit?: number;
            is_registration_open?: boolean;
        };
        RegistrationOrdersResponse: {
            total?: number;
            values?: components["schemas"]["RegistrationOrderResponse"][];
        };
        RegistrationOrderResponse: {
            id?: number;
            /** Format: date-time */
            created_at?: string;
            status?: components["schemas"]["OrderStatusResponse"];
            payment?: components["schemas"]["PaymentResponse"];
            tickets?: components["schemas"]["TicketResponse"][];
            answers?: {
                [key: string]: string;
            };
            promocodes?: string[];
        };
        OrderStatusResponse: {
            name?: string;
            title?: string;
        };
        PaymentResponse: {
            amount?: number;
            /** Format: date-time */
            paid_at?: string;
            payment_type?: string;
        };
        TicketResponse: {
            id?: number;
            number?: string;
            answers?: {
                [key: string]: string;
            };
            ticket_type?: components["schemas"]["TicketTypeResponse"];
            attendance?: components["schemas"]["AttendanceResponse"];
            place?: components["schemas"]["PlaceResponse"];
            codes?: components["schemas"]["CodesResponse"];
        };
        AttendanceResponse: {
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
        };
        PlaceResponse: {
            id?: string;
            description?: {
                [key: string]: unknown;
            };
        };
        CodesResponse: {
            ean13?: string;
            ean8?: string;
            printed_code?: string;
        };
        /** @description Описание создаваемого заказа */
        CreateOrder: {
            tickets?: components["schemas"]["TicketInclude"][];
            answers?: {
                [key: string]: string;
            };
            promocodes?: string[];
        };
        TicketInclude: {
            answers?: {
                [key: string]: unknown;
            };
            ticket_type_id?: string;
        };
        EditOrder: {
            visitors?: components["schemas"]["EditOrderVisitors"][];
            answers?: {
                [key: string]: unknown;
            };
            payment?: components["schemas"]["EditOrderPayment"];
        };
        EditOrderVisitors: {
            id?: number;
            answers?: {
                [key: string]: string;
            };
            attendance?: components["schemas"]["EditOrderAttendance"];
        };
        EditOrderPayment: {
            /** Format: date-time */
            paid_at?: string;
            amount?: number;
            payment_type?: string;
        };
        EditOrderAttendance: {
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
        };
        WebhooksApiResponse: {
            values?: components["schemas"]["WebhookApiResponse"][];
        };
        WebhookApiResponse: {
            id?: number;
            organization?: number;
            url?: string;
            type?: string;
            secret?: string;
        };
        CreateHook: {
            url: string;
            secret?: string;
            type: string;
        };
        EditHook: {
            url?: string;
            secret?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    introspectToken: {
        parameters: {
            query?: {
                /** @description Токен (безопаснее передавать в заголовке Authorization) */
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Introspect"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Список полей, которые нужно вывести */
                fields?: string[];
                /** @description Сколько элементов списка вывести */
                limit?: number;
                /** @description С какого элемента списка начать вывод */
                skip?: number;
                /** @description Поля сортировки (напр. +starts_at, -created_at) */
                sort?: string[];
                /** @description Категории, к которым принадлежат события */
                category_ids?: number[];
                category_ids_exclude?: number[];
                /** @description Города, события из которых выводить */
                cities?: string[];
                cities_exclude?: string[];
                organization_ids?: number[];
                organization_ids_exclude?: number[];
                event_ids?: number[];
                event_ids_exclude?: number[];
                /** @description Слова в названии или описании */
                keywords?: string[];
                keywords_exclude?: string[];
                /** @description Режимы доступа: private, draft, link_only, public. Доступно только организаторам */
                access_statuses?: ("private" | "draft" | "link_only" | "public")[];
                /** @description Уровни качества: featured, shown, hidden, not_moderated */
                moderation_statuses?: ("featured" | "shown" | "hidden" | "not_moderated")[];
                price_min?: number;
                price_max?: number;
                /** @description Событие начинается не раньше указанной даты */
                starts_at_min?: string;
                starts_at_max?: string;
                created_at_min?: string;
                created_at_max?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
        };
    };
    addEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvent"];
            };
        };
        responses: {
            /** @description Созданное событие */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    getSingleEvent: {
        parameters: {
            query?: {
                /** @description Список полей, которые нужно вывести */
                fields?: string[];
            };
            header?: never;
            path: {
                /** @description Номер события */
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    editEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Номер события */
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditEvent"];
            };
        };
        responses: {
            /** @description Обновлённое событие */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    getEventOrders: {
        parameters: {
            query?: {
                limit?: number;
                skip?: number;
                fields?: string[];
            };
            header?: never;
            path: {
                /** @description Номер события */
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOrdersResponse"];
                };
            };
        };
    };
    addOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Номер события */
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrder"];
            };
        };
        responses: {
            /** @description Созданный заказ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOrderResponse"];
                };
            };
        };
    };
    getSingleEventOrder: {
        parameters: {
            query?: {
                fields?: string[];
            };
            header?: never;
            path: {
                event_id: number;
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOrderResponse"];
                };
            };
        };
    };
    editEventOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditOrder"];
            };
        };
        responses: {
            /** @description Обновлённый заказ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOrderResponse"];
                };
            };
        };
    };
    addOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganization"];
            };
        };
        responses: {
            /** @description Созданная организация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    getHooks: {
        parameters: {
            query?: {
                /** @description Тип получаемых webhook'ов */
                type?: string;
            };
            header?: never;
            path: {
                /** @description Идентификатор организации */
                organization_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhooksApiResponse"];
                };
            };
        };
    };
    addHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор организации */
                organization_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhooksApiResponse"];
                };
            };
        };
    };
    getHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: number;
                /** @description Идентификатор webhook'а */
                hook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookApiResponse"];
                };
            };
        };
    };
    editHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: number;
                /** @description Идентификатор webhook'а */
                hook_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditHook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookApiResponse"];
                };
            };
        };
    };
}
